# This workflow does all the tagging, building, publishing etc. around a new release

name: Release

on:
  push:
    branches:
    - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  M2_SETTINGS: https://raw.githubusercontent.com/lukecmstevens/packages/master/.m2/settings.xml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    # Finalise the version by removing the -beta or -SNAPSHOT suffix if it exists

    - name: Finalise version
      run: scripts/finalise-version.sh

    - name: Download .m2 settings
      run: curl $M2_SETTINGS -O

    # Build and deploy maven package (including running tests)

    - name: Build with Maven
      run: mvn -B package -s settings.xml --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s settings.xml

    # Get maven properties and store in environment

    - name: Get version
      run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "MVN_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get artifactId
      run: |
          ARTIFACT=$( mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          echo "MVN_ARTIFACT=$ARTIFACT" >> $GITHUB_ENV

    # We finalised the version earlier, now committing, tagging, and pushing to main

    - name: Commit and tag version update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: Release version ${{ env.MVN_VERSION }}
        tagging_message: ${{ env.MVN_VERSION }}

    # Create a release and upload the jar to it

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.MVN_VERSION }}
        release_name: Release ${{ env.MVN_VERSION }}
        body_path: changelog.md

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/${{ env.MVN_ARTIFACT }}-${{ env.MVN_VERSION }}.jar
        asset_name: ${{ env.MVN_ARTIFACT }}-${{ env.MVN_VERSION }}.jar
        asset_content_type: application/java-archive

    # Switch to develop, bump version and commit

    - name: Switch to develop
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Bump version
      run: scripts/bump-version.sh

    - name: Commit and push bumped version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: develop
        commit_message: Bump version

        
